#!/usr/bin/env python3
"""Generate a hash-locked requirements file from an offline wheelhouse.

Run this after downloading wheels in the target Linux base image. It reads
package metadata from wheels rather than trusting their filenames.
"""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
import re
import sys
import zipfile


NAME_PATTERN = re.compile(r"^Name:\s*(.+)$", re.MULTILINE | re.IGNORECASE)
VERSION_PATTERN = re.compile(r"^Version:\s*(.+)$", re.MULTILINE | re.IGNORECASE)


def normalized(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name).lower()


def wheel_identity(path: Path) -> tuple[str, str]:
    with zipfile.ZipFile(path) as archive:
        # A wheel may vendor other distributions, each carrying a nested
        # ``*.dist-info/METADATA``. The distribution identity is the sole
        # METADATA directly below the wheel's top-level .dist-info directory.
        metadata_names = [
            name for name in archive.namelist()
            if name.endswith(".dist-info/METADATA")
            and len(Path(name).parts) == 2
        ]
        if len(metadata_names) != 1:
            raise ValueError(
                f"{path}: expected exactly one top-level .dist-info/METADATA"
            )
        metadata = archive.read(metadata_names[0]).decode("utf-8", "replace")
    name = NAME_PATTERN.search(metadata)
    version = VERSION_PATTERN.search(metadata)
    if not name or not version:
        raise ValueError(f"{path}: package metadata lacks Name or Version")
    return normalized(name.group(1).strip()), version.group(1).strip()


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--wheelhouse", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    wheels = sorted(args.wheelhouse.glob("*.whl"))
    if not wheels:
        raise SystemExit("wheelhouse has no wheels")
    locked: dict[str, tuple[str, str, str]] = {}
    for wheel in wheels:
        name, version = wheel_identity(wheel)
        record = (version, sha256(wheel), wheel.name)
        if name in locked and locked[name][:2] != record[:2]:
            raise SystemExit(
                f"multiple distributions for {name}; retain one target-platform wheel"
            )
        locked[name] = record
    lines = [
        "# Generated by docker/r0/generate_requirements_lock.py.",
        "# Do not edit: regenerate from the reviewed target-platform wheelhouse.",
    ]
    for name in sorted(locked):
        version, digest, filename = locked[name]
        lines.append(f"{name}=={version} --hash=sha256:{digest}  # {filename}")
    args.output.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {args.output} with {len(locked)} locked distributions")
    return 0


if __name__ == "__main__":
    sys.exit(main())
