# Written by Nikolay Dema <ndema2301@gmail.com>, Jun 2025

ARG base_img="nickodema/kobuki:humble-22.04-100625"

FROM ${base_img}

### ---------------------------------------------------------------------- #