# hsl_core/hsl_core/learning/__init__.py
"""Offline learning contracts; no runtime/ROS authority is exposed here."""

from .dirichlet import (
    DirichletBeliefTransition,
    TransitionPosterior,
    make_dirichlet_row,
)
from .evolution import (
    CandidateAssessment,
    EpisodeResult,
    EvolutionConfig,
    EvolutionGeneration,
    EvaluationPlan,
    EvaluationSplit,
    TacticalGenome,
    ValidationDecision,
    assess_paired_candidate,
    create_next_generation,
    mutate_genome,
    paired_student_t_interval,
    select_on_validation,
)
from .option_value import (
    DiscountedReturn,
    ExactOptionModel,
    FusionAssessment,
    KernelAtom,
    KernelEvidenceKind,
    OptionValueTable,
    ValueEntry,
    ValueUpdate,
    assess_exact_option_fusion,
    discounted_return,
)
from .transitions import (
    BaselineEvidence,
    CensoringStatus,
    DatasetManifest,
    FeatureSchema,
    FeatureState,
    OptionTransition,
    RewardComponent,
    RewardRateSegment,
    SplitAssignment,
    TransitionDataset,
    feature_state,
)

__all__ = [
    "BaselineEvidence",
    "CandidateAssessment",
    "CensoringStatus",
    "DatasetManifest",
    "DirichletBeliefTransition",
    "DiscountedReturn",
    "EpisodeResult",
    "EvolutionConfig",
    "EvolutionGeneration",
    "EvaluationPlan",
    "EvaluationSplit",
    "ExactOptionModel",
    "FeatureSchema",
    "FeatureState",
    "FusionAssessment",
    "KernelAtom",
    "KernelEvidenceKind",
    "OptionTransition",
    "OptionValueTable",
    "RewardComponent",
    "RewardRateSegment",
    "SplitAssignment",
    "TransitionDataset",
    "TransitionPosterior",
    "TacticalGenome",
    "ValidationDecision",
    "ValueEntry",
    "ValueUpdate",
    "assess_exact_option_fusion",
    "assess_paired_candidate",
    "create_next_generation",
    "discounted_return",
    "feature_state",
    "make_dirichlet_row",
    "mutate_genome",
    "paired_student_t_interval",
    "select_on_validation",
]
