# hsl_core/hsl_core/tactics/__init__.py
from .options import (
    ActionAdmission,
    ExecutionState,
    OptionAuditRecord,
    OptionAuthority,
    OptionContext,
    OptionDefinition,
    OptionGoal,
    OptionKind,
    OptionOutcome,
    OptionPhase,
    OptionRegistry,
    OptionResult,
    PredicateDecision,
)
from .fsm import (
    CandidateEvaluation,
    InterceptionTiming,
    MAX_TACTICAL_PROPOSALS,
    OptionProposal,
    SelectionResult,
    TacticalGuard,
    TacticalSelector,
    TacticalSnapshot,
)
from .utility import ROLE_FEATURES, UtilityProfile, UtilityResult, score

__all__ = [
    "ActionAdmission",
    "CandidateEvaluation",
    "ExecutionState",
    "InterceptionTiming",
    "MAX_TACTICAL_PROPOSALS",
    "OptionAuditRecord",
    "OptionAuthority",
    "OptionContext",
    "OptionDefinition",
    "OptionGoal",
    "OptionKind",
    "OptionOutcome",
    "OptionPhase",
    "OptionProposal",
    "OptionRegistry",
    "OptionResult",
    "PredicateDecision",
    "ROLE_FEATURES",
    "SelectionResult",
    "TacticalGuard",
    "TacticalSelector",
    "TacticalSnapshot",
    "UtilityProfile",
    "UtilityResult",
    "score",
]
